# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='learningsking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('descripton', models.TextField(blank=True, max_length=800, null=True)),
                ('similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowboard.learningsking')),
            ],
        ),
        migrations.CreateModel(
            name='learningsnowboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('descripton', models.TextField(blank=True, max_length=800, null=True)),
                ('similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowboard.learningsnowboarding')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('video_id', models.CharField(max_length=200, unique=True)),
                ('descripton', models.TextField(blank=True, max_length=800, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 5, 28, 22, 27, 44, 86594))),
            ],
        ),
        migrations.AddField(
            model_name='learningsnowboarding',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowboard.video'),
        ),
        migrations.AddField(
            model_name='learningsking',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowboard.video'),
        ),
    ]
