# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0004_auto_20160602_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 15, 9, 38, 845134)),
        ),
    ]
