# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0007_auto_20160604_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 4, 2, 9, 43, 186215)),
        ),
    ]
