# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0008_auto_20160604_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 5, 21, 57, 7, 548673)),
        ),
    ]
