# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0023_auto_20160607_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 22, 22, 10, 352754)),
        ),
    ]
