# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0025_auto_20160608_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 18, 17, 41, 614961)),
        ),
    ]
