# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0027_auto_20160608_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 18, 53, 11, 740032)),
        ),
    ]
