# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
