# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20160607_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
