# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sell', '0003_auto_20160607_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order_date', models.DateField(null=True)),
                ('payment_type', models.CharField(max_length=100, null=True)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='productorder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Cart'),
        ),
    ]
